/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include <stdio.h>
int fib()
{
    int number_1 = 1, number_2 = 2, number = 3, result = 2;
    while (number < 4 000 000)
    {
        printf("%d\n", number);
        if (number % 2 == 0)
        {
            result += number;
        }
        number_1 = number_2;
        number_2 = number;
        number = number_1 + number_2;
    }
    printf("%d\n", result);
}
int main()
{
    fib();
    return 0;
}
